name: 3D Modeler CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install OpenGL Dependencies
      run: |
        sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-utils

    - name: Install xvfb
      run: sudo apt-get install -y xvfb
        
    - name: Run PyOpenGL Test with Mesa
      run: |
           timeout 30 xvfb-run -a --server-args="-screen 0 1024x768x24" python test.py

